set nocompatible
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Plugins
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-repeat'
Plugin 'sheerun/vim-polyglot'
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'christoomey/vim-tmux-runner'

call vundle#end()            " required

filetype plugin indent on 

" Plugin configs
let g:ctrlp_user_command = 'ag %s -l --hidden --nocolor -g ""'
let g:ctrlp_use_caching = 0

" when indenting with '>', use 2 spaces width
set shiftwidth=2

" On pressing tab, insert 2 spaces
set expandtab

" Set clipboard
set clipboard=unnamed

" Set Line Number
set number
" set relativenumber

" Set theme
colo basic-dark 
" Normal mappings
nmap 0 ^
nmap <C-s> :w<cr>
nmap k gk
nmap j gj

" Insert mappings
imap jk <esc>
imap kj <esc>

" Leader mappings
let mapleader = "\<Space>"
nmap <leader>vr :tabe $MYVIMRC<cr>
nmap <leader>so :source $MYVIMRC<cr>
nnoremap <leader>- :wincmd _<cr>:wincmd \|<cr>
nnoremap <leader>= :wincmd =<cr>
map <leader>i mmgg=G'm<cr>
map <leader>p :set paste<cr>o<esc>"*]p:set nopaste<cr>

" Set autocommands
autocmd Filetype help nmap <buffer> q :q<CR>
autocmd VimResized * :wincmd =


