set nocompatible
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Plugins
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-repeat'
Plugin 'sheerun/vim-polyglot'
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'christoomey/vim-tmux-runner'
Plugin 'slim-template/vim-slim.git'
Plugin 'bling/vim-airline'                            
Plugin 'vim-airline/vim-airline-themes'              
Plugin 'tomasr/molokai'
Plugin 'tmux-plugins/vim-tmux-focus-events'
call vundle#end()            " required

syntax enable
filetype plugin indent on 

" Colour scheme
colorscheme molokai

" settings for terminal vim
if !has("gui_running")
  set t_Co=256
endif

" Plugin configs
let g:ctrlp_user_command = 'ag %s -l --hidden --nocolor -g ""'
let g:ctrlp_use_caching = 0

" when indenting with '>', use 2 spaces width
set shiftwidth=2

" On pressing tab, insert 2 spaces
set expandtab

" Set clipboard
set clipboard=unnamed

" Set Line Number
set number
" set relativenumber

" Search Settings
set incsearch
set hlsearch
set ignorecase
set smartcase

" Search Settings
set incsearch
set hlsearch
set ignorecase
set smartcase

" Set theme
colo basic-dark 

" Command aliases
command! Q q
command! E e

" Normal mappings
nmap 0 ^
nmap <C-s> :w<cr>
nmap <C-t> :tabnew<cr>
nmap k gk
nmap j gj
nmap <C-O> O<ESC>
nmap <CR> o<ESC>

" Insert mappings
imap jk <esc>
imap kj <esc>

" Leader mappings
let mapleader = "\<Space>"
nmap <leader>vr :tabe $MYVIMRC<cr>
nmap <leader>so :source $MYVIMRC<cr>
nmap <leader>h :nohlsearch<cr>
nnoremap <leader>- :wincmd _<cr>:wincmd \|<cr>
nnoremap <leader>= :wincmd =<cr>
map <leader>i mmgg=G'm<cr>
map <leader>p :set paste<cr>o<esc>"*]p:set nopaste<cr>

" Set autocommands
autocmd Filetype help nmap <buffer> q :q<CR>
autocmd VimResized * :wincmd =

" Triger `autoread` when files changes on disk
" https://unix.stackexchange.com/questions/149209/refresh-changed-content-of-file-opened-in-vim/383044#383044
" https://vi.stackexchange.com/questions/13692/prevent-focusgained-autocmd-running-in-command-line-editing-mode
autocmd FocusGained,BufEnter,CursorHold,CursorHoldI * if mode() != 'c' | checktime | endif
" Notification after file change
" https://vi.stackexchange.com/questions/13091/autocmd-event-for-autoread
autocmd FileChangedShellPost *
  \ echohl WarningMsg | echo "File changed on disk. Buffer reloaded." | echohl None
